# === OH MY ZSH ===

# Path to your oh-my-zsh installation.
export OH_MY_ZSH="$HOME/.oh-my-zsh"

# ZSH Theme https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Oh My ZSH config init
source $OH_MY_ZSH/oh-my-zsh.sh

# === SOURCE ===
export SH="$HOME/.config/sh"
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $SH/aliases
source $SH/exports
source $SH/functions

# === PLUGINS ===

# Standard plugins can be found in $OH_MY_ZSH/plugins/
# Custom plugins may be added to $OH_MY_ZSH/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# === MISC ===

# Required for pythonw to run Amulet Map Editor
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
    . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
  else
    export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
  fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Bashhub.com bash history
if [ -f ~/.bashhub/bashhub.zsh ]; then
  source ~/.bashhub/bashhub.zsh
fi

# https://github.com/pindexis/qfc file path auto-completion
[[ -s "$HOME/.qfc/bin/qfc.sh" ]] && source "$HOME/.qfc/bin/qfc.sh"
